"""initial_schema

Revision ID: ae7ba4bb04de
Revises: 
Create Date: 2026-06-18 17:09:31.770828

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae7ba4bb04de'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('applications',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('company', sa.Text(), nullable=False),
    sa.Column('position', sa.Text(), nullable=False),
    sa.Column('industry', sa.Text(), nullable=True),
    sa.Column('job_description', sa.Text(), nullable=True),
    sa.Column('job_url', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('date_applied', sa.String(length=10), nullable=True),
    sa.Column('salary_min', sa.Integer(), nullable=True),
    sa.Column('salary_max', sa.Integer(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('work_arrangement', sa.String(length=10), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=True),
    sa.Column('recruiter_name', sa.Text(), nullable=True),
    sa.Column('recruiter_email', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.String(length=32), nullable=False),
    sa.Column('updated_at', sa.String(length=32), nullable=False),
    sa.CheckConstraint("source IS NULL OR source IN ('linkedin','indeed','referral','direct','recruiter','other')", name='ck_application_source'),
    sa.CheckConstraint("status IN ('draft','applied','phone_screen','interview','final_round','offer','rejected','withdrawn')", name='ck_application_status'),
    sa.CheckConstraint("work_arrangement IS NULL OR work_arrangement IN ('remote','hybrid','onsite')", name='ck_application_work_arrangement'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('documents',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('filename', sa.Text(), nullable=False),
    sa.Column('original_path', sa.Text(), nullable=False),
    sa.Column('file_type', sa.String(length=20), nullable=False),
    sa.Column('file_size_bytes', sa.Integer(), nullable=True),
    sa.Column('checksum_sha256', sa.String(length=64), nullable=True),
    sa.Column('source_type', sa.String(length=30), nullable=False),
    sa.Column('ingestion_status', sa.String(length=20), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.String(length=32), nullable=False),
    sa.Column('processed_at', sa.String(length=32), nullable=True),
    sa.CheckConstraint("file_type IN ('pdf','docx','txt','md','json','github_repo')", name='ck_document_file_type'),
    sa.CheckConstraint("ingestion_status IN ('pending','processing','complete','failed','skipped')", name='ck_document_status'),
    sa.CheckConstraint("source_type IN ('resume','cover_letter','job_description','github','claude_export','answer_bank','other')", name='ck_document_source_type'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('checksum_sha256')
    )
    op.create_table('experiences',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('company', sa.Text(), nullable=False),
    sa.Column('employment_type', sa.String(length=20), nullable=False),
    sa.Column('start_date', sa.String(length=10), nullable=False),
    sa.Column('end_date', sa.String(length=10), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('location', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.String(length=32), nullable=False),
    sa.Column('updated_at', sa.String(length=32), nullable=False),
    sa.CheckConstraint("employment_type IN ('full_time','part_time','contract','internship','freelance')", name='ck_experience_employment_type'),
    sa.CheckConstraint("source IN ('manual','resume_import','linkedin','document_import')", name='ck_experience_source'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('knowledge_graph_nodes',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('node_type', sa.String(length=20), nullable=False),
    sa.Column('entity_id', sa.String(length=32), nullable=False),
    sa.Column('label', sa.Text(), nullable=False),
    sa.Column('properties', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.String(length=32), nullable=False),
    sa.CheckConstraint("node_type IN ('experience','skill','project','company','application','document','answer')", name='ck_kg_node_type'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('projects',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('industry', sa.Text(), nullable=True),
    sa.Column('repository_url', sa.Text(), nullable=True),
    sa.Column('tech_stack', sa.JSON(), nullable=False),
    sa.Column('start_date', sa.String(length=10), nullable=True),
    sa.Column('end_date', sa.String(length=10), nullable=True),
    sa.Column('is_ongoing', sa.Boolean(), nullable=False),
    sa.Column('confidence_level', sa.String(length=20), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('created_at', sa.String(length=32), nullable=False),
    sa.Column('updated_at', sa.String(length=32), nullable=False),
    sa.CheckConstraint("confidence_level IN ('verified','strong_inference','weak_inference')", name='ck_project_confidence'),
    sa.CheckConstraint("source IN ('manual','github','document_import','claude_export')", name='ck_project_source'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('questions',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('question_template', sa.Text(), nullable=False),
    sa.Column('industry', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=20), nullable=False),
    sa.Column('length_target', sa.String(length=10), nullable=False),
    sa.Column('variables', sa.JSON(), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.String(length=32), nullable=False),
    sa.CheckConstraint("category IN ('behavioral','technical','situational','motivational','cultural','role_specific')", name='ck_question_category'),
    sa.CheckConstraint("length_target IN ('short','medium','long')", name='ck_question_length'),
    sa.CheckConstraint("source IN ('manual','job_description','generated','import')", name='ck_question_source'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('resume_templates',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('target_industry', sa.Text(), nullable=True),
    sa.Column('layout_type', sa.String(length=20), nullable=False),
    sa.Column('template_json', sa.JSON(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.String(length=32), nullable=False),
    sa.CheckConstraint("layout_type IN ('single_column','two_column','hybrid')", name='ck_template_layout'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('skills',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=20), nullable=False),
    sa.Column('proficiency', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.String(length=32), nullable=False),
    sa.Column('updated_at', sa.String(length=32), nullable=False),
    sa.CheckConstraint("category IN ('programming','data','domain','soft','tool','methodology')", name='ck_skill_category'),
    sa.CheckConstraint("proficiency IN ('exposure','beginner','intermediate','advanced','expert')", name='ck_skill_proficiency'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('system_config',
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('writing_profiles',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('tone_descriptors', sa.JSON(), nullable=False),
    sa.Column('structure_patterns', sa.JSON(), nullable=False),
    sa.Column('vocabulary_patterns', sa.JSON(), nullable=False),
    sa.Column('sample_sentences', sa.JSON(), nullable=False),
    sa.Column('source_doc_ids', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.String(length=32), nullable=False),
    sa.Column('updated_at', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('answers',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('question_id', sa.String(length=32), nullable=False),
    sa.Column('application_id', sa.String(length=32), nullable=True),
    sa.Column('original_answer', sa.Text(), nullable=False),
    sa.Column('edited_answer', sa.Text(), nullable=True),
    sa.Column('diff_summary', sa.Text(), nullable=True),
    sa.Column('confidence_level', sa.String(length=20), nullable=False),
    sa.Column('evidence_ids', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.String(length=32), nullable=False),
    sa.Column('updated_at', sa.String(length=32), nullable=False),
    sa.CheckConstraint("confidence_level IN ('verified','strong_inference','weak_inference')", name='ck_answer_confidence'),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('application_timeline',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('application_id', sa.String(length=32), nullable=False),
    sa.Column('event_type', sa.String(length=30), nullable=False),
    sa.Column('from_status', sa.String(length=20), nullable=True),
    sa.Column('to_status', sa.String(length=20), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('event_date', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.String(length=32), nullable=False),
    sa.CheckConstraint("event_type IN ('status_change','note_added','document_attached','interview_scheduled','outcome_recorded')", name='ck_timeline_event_type'),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('experience_bullets',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('experience_id', sa.String(length=32), nullable=False),
    sa.Column('bullet_text', sa.Text(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('confidence_level', sa.String(length=20), nullable=False),
    sa.Column('evidence_ids', sa.Text(), nullable=False),
    sa.Column('created_at', sa.String(length=32), nullable=False),
    sa.CheckConstraint("confidence_level IN ('verified','strong_inference','weak_inference')", name='ck_bullet_confidence'),
    sa.ForeignKeyConstraint(['experience_id'], ['experiences.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('experience_skills',
    sa.Column('experience_id', sa.String(length=32), nullable=False),
    sa.Column('skill_id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['experience_id'], ['experiences.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('experience_id', 'skill_id')
    )
    op.create_table('generation_logs',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('generation_type', sa.String(length=20), nullable=False),
    sa.Column('application_id', sa.String(length=32), nullable=True),
    sa.Column('prompt_name', sa.Text(), nullable=False),
    sa.Column('prompt_version', sa.String(length=20), nullable=False),
    sa.Column('model', sa.Text(), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.String(length=32), nullable=False),
    sa.CheckConstraint("generation_type IN ('resume','cover_letter','answer','copilot','ats_analysis')", name='ck_gen_log_type'),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ingestion_logs',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('document_id', sa.String(length=32), nullable=False),
    sa.Column('stage', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.String(length=32), nullable=False),
    sa.CheckConstraint("stage IN ('parse','normalize','extract_entities','embed','link_graph')", name='ck_ingestion_stage'),
    sa.CheckConstraint("status IN ('success','failure','skipped')", name='ck_ingestion_status'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('knowledge_graph_edges',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('from_node_id', sa.String(length=32), nullable=False),
    sa.Column('to_node_id', sa.String(length=32), nullable=False),
    sa.Column('edge_type', sa.String(length=30), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('properties', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.String(length=32), nullable=False),
    sa.CheckConstraint("edge_type IN ('has_skill','uses_technology','worked_at','produced','evidenced_by','applied_to','answered_for','resulted_in','related_to')", name='ck_kg_edge_type'),
    sa.ForeignKeyConstraint(['from_node_id'], ['knowledge_graph_nodes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_node_id'], ['knowledge_graph_nodes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project_skills',
    sa.Column('project_id', sa.String(length=32), nullable=False),
    sa.Column('skill_id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('project_id', 'skill_id')
    )
    op.create_table('resumes',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('application_id', sa.String(length=32), nullable=True),
    sa.Column('template_id', sa.String(length=32), nullable=True),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('content_json', sa.JSON(), nullable=False),
    sa.Column('file_path', sa.Text(), nullable=True),
    sa.Column('ats_score', sa.Float(), nullable=True),
    sa.Column('word_count', sa.Integer(), nullable=True),
    sa.Column('page_count', sa.Integer(), nullable=False),
    sa.Column('is_master', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.String(length=32), nullable=False),
    sa.Column('updated_at', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['template_id'], ['resume_templates.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('skill_evidence',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('skill_id', sa.String(length=32), nullable=False),
    sa.Column('source_type', sa.String(length=20), nullable=False),
    sa.Column('source_id', sa.String(length=32), nullable=False),
    sa.Column('evidence_text', sa.Text(), nullable=False),
    sa.Column('confidence_level', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.String(length=32), nullable=False),
    sa.CheckConstraint("confidence_level IN ('verified','strong_inference','weak_inference')", name='ck_evidence_confidence'),
    sa.CheckConstraint("source_type IN ('experience','project','github','document','self_reported')", name='ck_evidence_source_type'),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('outcome_signals',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('application_id', sa.String(length=32), nullable=False),
    sa.Column('resume_id', sa.String(length=32), nullable=True),
    sa.Column('signal_type', sa.String(length=20), nullable=False),
    sa.Column('signal_weight', sa.Float(), nullable=False),
    sa.Column('template_used', sa.Text(), nullable=True),
    sa.Column('ats_score', sa.Float(), nullable=True),
    sa.Column('industry', sa.Text(), nullable=True),
    sa.Column('position_type', sa.Text(), nullable=True),
    sa.Column('created_at', sa.String(length=32), nullable=False),
    sa.CheckConstraint("signal_type IN ('no_response','rejected','phone_screen','interview','final_round','offer','accepted')", name='ck_outcome_signal_type'),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resume_id'], ['resumes.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('outcome_signals')
    op.drop_table('skill_evidence')
    op.drop_table('resumes')
    op.drop_table('project_skills')
    op.drop_table('knowledge_graph_edges')
    op.drop_table('ingestion_logs')
    op.drop_table('generation_logs')
    op.drop_table('experience_skills')
    op.drop_table('experience_bullets')
    op.drop_table('application_timeline')
    op.drop_table('answers')
    op.drop_table('writing_profiles')
    op.drop_table('system_config')
    op.drop_table('skills')
    op.drop_table('resume_templates')
    op.drop_table('questions')
    op.drop_table('projects')
    op.drop_table('knowledge_graph_nodes')
    op.drop_table('experiences')
    op.drop_table('documents')
    op.drop_table('applications')
    # ### end Alembic commands ###
