"""phase8 optimization tables

Revision ID: bd8b1c798504
Revises: ae7ba4bb04de
Create Date: 2026-06-20 07:00:24.419729

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd8b1c798504'
down_revision: Union[str, None] = 'ae7ba4bb04de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ab_experiments',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('target_engine', sa.String(length=20), nullable=False),
    sa.Column('metric', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('winner_variant_id', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.String(length=32), nullable=False),
    sa.Column('concluded_at', sa.String(length=32), nullable=True),
    sa.CheckConstraint("status IN ('running','concluded')", name='ck_ab_experiment_status'),
    sa.CheckConstraint("target_engine IN ('resume','ats','rag','cover_letter','copilot')", name='ck_ab_experiment_engine'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('optimization_proposals',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('target_engine', sa.String(length=20), nullable=False),
    sa.Column('target_parameter', sa.Text(), nullable=False),
    sa.Column('current_value', sa.Text(), nullable=True),
    sa.Column('proposed_value', sa.Text(), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('expected_impact', sa.Text(), nullable=False),
    sa.Column('confidence_level', sa.String(length=20), nullable=False),
    sa.Column('risk_level', sa.String(length=10), nullable=False),
    sa.Column('evidence_json', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.String(length=32), nullable=False),
    sa.Column('updated_at', sa.String(length=32), nullable=False),
    sa.Column('decided_at', sa.String(length=32), nullable=True),
    sa.CheckConstraint("confidence_level IN ('verified','strong_inference','weak_inference')", name='ck_opt_proposal_confidence'),
    sa.CheckConstraint("risk_level IN ('low','medium','high')", name='ck_opt_proposal_risk'),
    sa.CheckConstraint("status IN ('pending','approved','rejected','reverted')", name='ck_opt_proposal_status'),
    sa.CheckConstraint("target_engine IN ('resume','ats','rag','cover_letter','copilot')", name='ck_opt_proposal_engine'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prompt_versions',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('prompt_name', sa.Text(), nullable=False),
    sa.Column('version', sa.String(length=20), nullable=False),
    sa.Column('content_yaml', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('parent_version', sa.String(length=20), nullable=True),
    sa.Column('change_rationale', sa.Text(), nullable=True),
    sa.Column('created_at', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('prompt_name', 'version', name='uq_prompt_name_version')
    )
    op.create_table('ab_variants',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('experiment_id', sa.String(length=32), nullable=False),
    sa.Column('label', sa.String(length=20), nullable=False),
    sa.Column('config_json', sa.Text(), nullable=False),
    sa.Column('impressions', sa.Integer(), nullable=False),
    sa.Column('conversions', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['experiment_id'], ['ab_experiments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('optimization_logs',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('proposal_id', sa.String(length=32), nullable=True),
    sa.Column('action', sa.String(length=10), nullable=False),
    sa.Column('target_engine', sa.String(length=20), nullable=False),
    sa.Column('target_parameter', sa.Text(), nullable=False),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('actor', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.String(length=32), nullable=False),
    sa.CheckConstraint("action IN ('applied','reverted')", name='ck_opt_log_action'),
    sa.ForeignKeyConstraint(['proposal_id'], ['optimization_proposals.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('optimization_logs')
    op.drop_table('ab_variants')
    op.drop_table('prompt_versions')
    op.drop_table('optimization_proposals')
    op.drop_table('ab_experiments')
    # ### end Alembic commands ###
